<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('SELECT_GROUP'); ?></div>
        </div>
    </div>
    <!--Groups Tables-->
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <tr>
                    <td class="icon"><img src="/images/group1.png" class="" alt="group1" /></td>
                    <td class="body"><a href="<?php echo $this->baseurl(); ?>groups/select/g/<?php echo 1; ?>"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></a></td>
                </tr>
                <tr>
                    <td class="icon"><img src="/images/group2.png" class="" alt="group1" /></td>
                    <td class="body"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></td>
                </tr>
                <tr>
                    <td class="icon"><img src="/images/group3.png" class="" alt="group1" /></td>
                    <td class="body"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>