<div class="container-fluid progress-body">
    <!--Title-->
    <div class="row">
        <div class="second-header progress-header">
            <img src="/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('GROUPS_PROGRESS'); ?></div>
        </div>
    </div>
    <!--Groups Tables-->
    <div class="row">
        <table class="table table-groups progress-table">
            <tbody>
                <tr>
                    <td class="icon"><img src="/images/groups/group1.png" class="" alt="group1" /></td>
                    <td class="body"><a href="<?php echo $this->baseurl(); ?>groups/group/g/<?php echo 1; ?>"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></a></td>
                </tr>
                <tr>
                    <td class="icon"><img src="/images/groups/group2.png" class="" alt="group2" /></td>
                    <td class="body"><a href="<?php echo $this->baseurl(); ?>groups/group/g/<?php echo 2; ?>"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></a></td>
                </tr>
                <tr>
                    <td class="icon"><img src="/images/groups/group3.png" class="" alt="group3" /></td>
                    <td class="body"><a href="<?php echo $this->baseurl(); ?>groups/group/g/<?php echo 3; ?>"><div class="big-title">Title</div><span class="small-title">aka, sdd, dfd fd, defdf</span></a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>