<div class="container-fluid HP">
    <div class="row">
        <div class="col-md-6 register-WR pull-right text-right">
            <div class="register-link"><a href="/"><?php echo $this->lang->_('LOGIN'); ?></a></div>
            <div class="col-md-5 col-md-offset-5 register-dash">
                <h1><?php echo $this->lang->_('SITE_TITLE'); ?></h1>
                <div><?php echo $this->register_form; ?></div>
            </div>
        </div>
        <div class="col-md-6">IMAGE</div>
    </div>
</div>