<div class="container">
    <div class="navbar-header rel text-center">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only"><?php echo $this->lang->_('MENU'); ?></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand text-center"><img class="logo" src="/images/logo.png" alt="ba-la-gan" /></a>
        <button onclick="window.history.back()" class="back"><img src="/images/back.png" alt="back" /></button>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->baseurl(); ?>groups" title=""><?php echo $this->lang->_('MY_GROUPS'); ?></a></li>
            <li><a href="<?php echo $this->baseurl(); ?>students" title=""><?php echo $this->lang->_('STUDENTS_PROGRESS'); ?></a></li>
            <li><a href="<?php echo $this->baseurl(); ?>groups" title=""><?php echo $this->lang->_('DONE_ACTIONE'); ?></a></li>
            <li><a href="<?php echo $this->baseurl(); ?>logout" title=""><?php echo $this->lang->_('LOGOUT'); ?></a></li>
        </ul>
    </nav>
</div>