<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html manifest="offline.manifest">
    <head>
        <title><?php echo $this->lang->_('SITE_TITLE'); ?></title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <!-- CSS -->
        <link type="text/css" rel="stylesheet" href="/fonts/font-awesome-4.2.0/css/font-awesome.min.css">
        <link type="text/css" rel="stylesheet" href="/css/bootstrap/bootstrap-rtl.min.css">
        <link type="text/css" rel="stylesheet" href="/css/style.css">
    </head>
    
    <body>
        <!--header-->
        <?php if( Zend_Auth::getInstance()->hasIdentity() ) : ?>
        <header class="navbar" id="header" role="banner">
            <?php echo $this->partial('header.phtml', array('lang' => $this->lang));?>
        </header>
        <?php endif; ?>
        <!-- BODY -->
        <div id="body" data-ng-app="BalaganApp"><?php echo $this->layout()->content; ?></div>
        <!-- FOOTER -->
        <footer>
            <!-- JS -->
            <script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
            <script type="text/javascript" src="/js/bootstrap/bootstrap-rtl.min.js"></script>
            <script type="text/javascript" src="/js/angular.min.js"></script>
            <script type="text/javascript" src="/js/angular-ui-router.min.js"></script>
            <script type="text/javascript" src="/js/app.js"></script>
            
            <script type="text/javascript" src="/js/jquery-validation/jquery.validate.min.js"></script>
            <script type="text/javascript" src="/js/jquery-validation/additional-methods.min.js"></script>
            <script type="text/javascript" src="/js/jquery-validation/messages_he.js"></script>
        </footer>
    </body>
</html>